### PR TITLE
I20 fix decodingparams

### PR DESCRIPTION
**Pull request by abhidg**

### CODE REVIEW

**Comment by abhidg** [comment]
@brianzhang01 could you take a look at the regression test in test_HMM.cpp? I added that to increase codecov, but it fails. The regression test in TESTS/regression_test.py does work though.

**Comment by brianzhang01** [comment]
Thanks for asking me to take a look. I spent around 1.5 hours but have figured it out -- params.doPosteriorSums needs to be set to true before starting the decoding, as can be seen [here](https://github.com/OxfordRSE/ASMC/blob/8c0b414897dd05d3d0d9e0368a23a3fa009f3d43/ASMC_SRC/TESTS/regression_test.py#L32). There still is an additional rounding issue, which I'm working on fixing now.

**Comment by brianzhang01** [comment]
So I've just pushed a commit which should run the tests again soon and hopefully come up as passing. A few comments.
- Great idea to add this in the first place and increase code coverage, I'm very happy about that
- I had to move the default arguments in the second constructor from DecodingParams.cpp file to DecodingParams.hpp. I think it was a mistake to put them in DecodingParams.cpp earlier, is this right?
- The regression test takes a while, I'm wondering if it makes sense to not have it compile to `ASMC_unit_tests` but instead two separate binaries for unit test vs. regression test? I get the output message
```
Decoding progress: 100%  (44850/44850)
Decoded 44850 pairs in 387.558138565 seconds.
```
- I left some stuff in there that I used for debugging, feel free to remove that and clean it up
- Right now we should really make sure the user calls processOptions if they choose to use the empty (default) constructor for DecodingParams, right after they've set the fields that are necessary. At first I suspected this as the issue, which is why I'm no longer calling the default constructor. Currently the empty constructor is still used by main.cpp. We can also delete the empty constructor and have a constructor that takes in `int argc, char* argv[]` which basically does what `processCommandLineArgs` currently does, which might be my preference.

**Comment by brianzhang01** [comment]
Thanks, sounds great! The only downside I see to removing the default constructor is that C++ does not have named arguments. This leads to long argument lists to the constructor, whereas before we could just initialize, set the few arguments we need by name, and then call processOptions. See the new `test_decoding_params.cpp` for an example of how things are a bit more cumbersome. Still, I'm in favor of removing the default constructor.

**Comment by abhidg** [comment]
@brianzhang01 Maybe it's worth separating out processing and pure data. We could have a `DecodingParamsValues` which is a struct with default values that the user can override. `DecodingParams` would take this and call processOptions().

The other option (possibly more C++ like) is to set `DecodingParams` members to private and use setter methods.

**Comment by brianzhang01** [comment]
I like both of the suggestions. It's a bit low-priority for me and I'm happy for things to stay as they are, especially since I'll most likely be calling the constructor from Python which does allow named arguments.

**Pull request merged**
